// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzr85jPExzZs3cpyF9R-xA_h0f783zmA',
    appId: '1:268802509862:web:8e688673b4b3ff61adaae7',
    messagingSenderId: '268802509862',
    projectId: 'ditokokuid-a2ff4',
    authDomain: 'ditokokuid-a2ff4.firebaseapp.com',
    storageBucket: 'ditokokuid-a2ff4.firebasestorage.app',
    measurementId: 'G-EHQ1MQ0QNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAaZMiI4Tb_kNFFIhtq4msd0a9fij3iaM',
    appId: '1:268802509862:android:217c4d9148a38f94adaae7',
    messagingSenderId: '268802509862',
    projectId: 'ditokokuid-a2ff4',
    storageBucket: 'ditokokuid-a2ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_CPkLniagmmpLFRNvOunipShNcOCTFo',
    appId: '1:268802509862:ios:8ad4c7b3b8caea45adaae7',
    messagingSenderId: '268802509862',
    projectId: 'ditokokuid-a2ff4',
    storageBucket: 'ditokokuid-a2ff4.firebasestorage.app',
    androidClientId: '268802509862-0spigpegpcaofsgrqbl24opein5fm7jr.apps.googleusercontent.com',
    iosClientId: '268802509862-62ub9ete4k7e6e7c5vqi9hm7uirbh9pf.apps.googleusercontent.com',
    iosBundleId: 'customer.ditokoku.id',
  );

}